FORUM/community/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('forum/',include('forum.urls')),
    path('',include('userprofile.urls')),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FORUM/forum/urls.py
from . import views
from django.urls import path
from django.urls import re_path
from django.conf.urls import url
app_name = "forum"

base64_pattern = r'(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'

urlpatterns = [

   path('',views.home,name="home"), 
   path('new_forum/',views.new_forum,name="new_forum"), 
   path('new_thread/',views.new_thread,name="new_thread"), 
   path('profile/',views.profile,name="profile"), 
   path('open_thread/<str:t_id>/', views.open_thread, name='open_thread'),
   path('delete_thread/<str:t_id>/', views.delete_thread, name='delete_thread'),
   path('delete_reply/<str:r_id>/', views.delete_reply, name='delete_reply'),
   path('open_forum/<str:f_id>/', views.open_forum, name='open_forum'),
   path('join_forum/', views.join_forum, name='join_forum'),
   path('exit_forum/', views.exit_forum, name='exit_forum'),
   path('reply/',views.reply,name="reply"), 
   re_path(r'^(?P<base64string>{})'.format(base64_pattern),views.forum_view,name="forum_view"),
]

FORUM/forum/models.py
from django.db import models 

#parent model
class forum(models.Model):
    name=models.CharField(max_length=200,default="anonymous" )
    fid = models.AutoField(primary_key=True)
    email=models.CharField(max_length=200,null=True)
    topic= models.CharField(null = True,max_length=300)
    description = models.CharField(null = True,max_length=1000,blank=True)
    link = models.CharField(null = True,max_length=100)
    date_created=models.DateField(auto_now_add=True,null=True)
    privacy = models.CharField(null= True,max_length=100,default="Private")

class Thread(models.Model):
    forum = models.ForeignKey(forum,blank=True,on_delete=models.CASCADE)
    name=models.CharField(max_length=200,default="anonymous" )
    tid = models.AutoField(primary_key=True)
    email=models.CharField(max_length=200,null=True)
    topic= models.CharField(null = True,max_length=300)
    description = models.CharField(null = True,max_length=1000,blank=True)
    link = models.CharField(null = True,max_length=100)
    date_created=models.DateField(auto_now_add=True,null=True)
    privacy = models.CharField(null= True,max_length=100,default="Private")

#child model
class Reply_thread(models.Model):
    thread = models.ForeignKey(Thread,blank=True,on_delete=models.CASCADE)
    name=models.CharField(max_length=200,default="anonymous" )
    email=models.CharField(max_length=200,null=True)
    repid = models.AutoField(primary_key=True)
    reply = models.CharField(max_length=1000)


class memeber_info(models.Model):
    forum = models.ForeignKey(forum,blank=True,on_delete=models.CASCADE)
    email = models.CharField(max_length=200,null=True)
    name=models.CharField(max_length=200,default="anonymous" )

FORUM/forum/views.py
from django.shortcuts import render,redirect
from forum.models import * 
from django.contrib.auth.models import User
from datetime import date
import secrets
from django.http import HttpResponseRedirect

def home(request):
    try:
        item = forum.objects.all()
    except:
        item = None
    return render(request,"index.html",{'item':item})

def new_forum(request):
    if request.method == 'POST':
        today = date.today()
        d1 = today.strftime("%d/%m/%Y")
        current_user = request.user
        name = request.POST.get("name")
        pri  = request.POST.get("privacy")
        email = current_user.email
        topic = request.POST.get("topic")
        description = request.POST.get("description")


        new_entry = forum(
            name = name,
            email = email,
            topic = topic,
            description = description,
            date_created = d1,
            privacy = pri,
            link = "forum/"+secrets.token_urlsafe(11),
        )

        new_entry.save()
        f = forum.objects.get(email = email, name = name, topic = topic,description = description,privacy = pri)
        f_id = f.fid
        new_entry1 = memeber_info(
                name = name,
                forum_id = f_id,
                email = email,)
        new_entry1.save()
        try:
            item = forum.objects.all()
        except:
            item = None


    return redirect('home')


def forum_view(request,base64string):
    return render(request,"dyna.html")

def profile(request):
    current_user = request.user
    count = 0
    try:
            item = forum.objects.filter(email = current_user.email )
            for i in item:
                count=count+1
    except:
            item = None
    try:
            memb = memeber_info.objects.filter(email = current_user.email )
            dic = []
            for i in memb:
                f = memeber_info.objects.get(fid = i.forum_id)
                print(f.topic)
                dic.append(f.topic)


    except:
            memb = None
    print(memb)

    return render(request,"profile.html",{'user':current_user,'count':count,'dic':dic})


def open_thread(request,t_id):
    current_user = request.user
    email = current_user.email
    t_id = int(t_id)
    try:
        thread = Thread.objects.get(tid = t_id)
    except:
        thread = None
    try:
        r1 = Reply_thread.objects.filter(thread_id = t_id,email = email)
    except:
        r1 = None
    try:
        r2 = Reply_thread.objects.filter(thread_id = t_id).exclude(email = email)
    except:
        r2 = None
    return render(request,"open_thread.html",{'thread':thread,'r1':r1,'r2':r2})

def reply(request):
    if request.method == 'POST':
        current_user = request.user
        email = current_user.email
        thread_id = request.POST.get("thread_id")
        reply = request.POST.get("reply")
        obj1 = Thread.objects.get(tid = thread_id)
        f_id = obj1.forum_id
        print(thread_id)
        print(f_id)
        
        try:
            obj = memeber_info.objects.get(email = email, forum_id = f_id)
            
            name = obj.name

            new_entry = Reply_thread(
                name = name,
                email = email,
                thread_id = thread_id,
                reply = reply,
            )

            new_entry.save()
        except:
            obj = None

    return open_thread(request,thread_id)

def join_forum(request):
    if request.method == 'POST':
        name = request.POST.get("name1")
        f_id = request.POST.get("forum_id1")
        current_user = request.user
        email = current_user.email
        try:
            obj = memeber_info.objects.get(email = email, forum_id = f_id)
        except memeber_info.DoesNotExist:
            new_entry = memeber_info(
                name = name,
                forum_id = f_id,
                email = email,)
            new_entry.save()
        try:
            f = forum.objects.get(fid = f_id)
        except:
            f = None
        try:
            t = Thread.objects.filter(forum_id = f_id)
        except:
            t = None
        try:
            m = memeber_info.objects.filter(forum_id = f_id)
        except:
            m = None
    return render(request,"forum.html",{'forum':f,'thread':t,'member':m})

def new_thread(request):
    if request.method == 'POST':
        today = date.today()
        d1 = today.strftime("%d/%m/%Y")
        current_user = request.user
        email = current_user.email
        topic = request.POST.get("topic")
        forum_id = request.POST.get("forum_id")
        description = request.POST.get("description")
        try:
            obj = memeber_info.objects.get(email = email, forum_id = forum_id)
            name = obj.name
            new_entry = Thread(
                name = name,
                email = email,
                topic = topic,
                description = description,
                date_created = d1,
                forum_id = forum_id,
            )

            new_entry.save()
        except:
            obj = None


    return open_forum(request,forum_id)

def open_forum(request,f_id):
    current_user = request.user
    email = current_user.email
    try:
        checker = memeber_info.objects.get(forum_id = f_id,email=email)
    except:
        checker = None
    try:
        f = forum.objects.get(fid = f_id)
    except:
        f = None
    try:
        t1 = Thread.objects.filter(forum_id = f_id,email = email)
    except:
        t1 = None
    try:
        t2 = Thread.objects.filter(forum_id = f_id).exclude(email = email)
    except:
        t2 = None
    try:
        m = memeber_info.objects.filter(forum_id = f_id)
    except:
        m = None
    return render(request,"forum.html",{'forum':f,'thread1':t1,'thread2':t2,'member':m,'checker':checker})

def exit_forum(request):
    current_user = request.user
    email = current_user.email
    if request.method == 'POST':
        f_id = request.POST.get("forum_id2")
        try:
            f = memeber_info.objects.get(forum_id = f_id, email = email)
            f.delete()
        except:
            f = None
    return redirect('home')

def delete_thread(request,t_id):
    current_user = request.user
    email = current_user.email
    try:
        f = Thread.objects.get(tid = t_id)
        f_id = f.forum_id
        f.delete()
    except:
        f = None
    print(f)
    return open_forum(request,f_id)

def delete_reply(request,r_id):
    current_user = request.user
    email = current_user.email
    try:
        f = Reply_thread.objects.get(repid = r_id)
        t_id = f.thread_id
        f.delete()
    except:
        f = None
    return open_thread(request,t_id)

FORUM/templates/dyna.html
{% extends 'base.html'%}

{% block content %}
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-lg-offset-0">
                <div class="card-body">
                        <h1 class="card-title">Posts</h1>
                </div>
                {% if user.is_authenticated%}
                    <div class="row">
                        <div class="col-lg-3">
                            <a href="#newModal" data-toggle="modal" class="btn btn-primary" title="Add Thread">
                                 Make a new Thread
                            </a>
                        </div>
                    </div>
                {%endif%}
                {%if item%}
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Description</th>
                        <th scope="col">Last Post</th>
                        <th scope="col">Privacy</th>
                        <th>Reply</th>
                      </tr>
                    </thead>
                    <tbody>
                    {%for info in item%}
                      <tr>
                        <td><a href="{{info.link}}" style="font-size: 18px;" class="blue">{{info.name}}</a></td>
                        <td> {{info.description}} </td>
                        <td> {{info.date_created}} </td>
                        <td>{{info.privacy}}</td>
                        {% if user.is_authenticated%}
                        <td> <button id={{info.tid}} onclick="openThread(this);" class="btn btn-primary">Reply</button></td>
                        {%endif%}
                        
                    </tr>
                    {%endfor%}
                    </tbody>
                  </table>
                {%endif%}

    <div class="modal fade" id="newModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <form action="" method="POST" role="form">
                        <div class="form-group">
                            <label for="ForumName">Title</label>
                            <br>
                                <input type="text" id="ForumName" name = "ForumName" minlength="3"><br><br>
                        </div>
                        <div class="form-group" >
                            <label for="description">Description</label>
                            <br>
                            <input type="text" id="description" name = "description" size="20px"><br><br>
                        </div>
                        <div class="form-group" >
                        
                            <label for="Privacy">Privacy</label>
                            <br>
                            <label for="Private">Private</label>
                            <input type="radio" id="Private" value="Private" name="privacy">    
                            <label for="Public">Public</label>
                            <input type="radio" id="Public" value="Public" name="privacy">
                        </div>
                        
                        <button type="submit" formaction="{% url 'forum:new_forum' %}" class="btn btn-primary">
                            {% csrf_token %}
                            Submit</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <script>
        function openThread(what) {
            var m = what.id;
            console.log(m);
            document.location.href = "{% url 'forum:open_thread' 1234 %}".replace(/1234/, m.toString());
        }
    </script>

 {% endblock %}   

FORUM/templates/forum.html
{% extends 'base.html'%}

{% block content %}
<style>
    a{
        color: white;
    }
    .container
    {
        padding:30px 30px 0 30px ;
    }
    #home,#profile
    {
        background-color: white;
    }
    #myTabContent
    {
        width: 500px;
    }
    #first
    {
        margin-left: 0;
    }
</style>






<div class="container">
                    <h3 style="color: white;text-align: center;"><strong>FORUM: {{forum.topic}}</strong></h3>
                    <br>
                    {%if thread1 or thread2%}
                        <table class="table">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">Thread Name </th>
                                <th scope="col">Description</th>
                                <th scope="col">Posted on</th>
                                <th>Reply</th>
                            </tr>
                            </thead>
                            <tbody>
                            {%for info in thread1%}
                                <tr>
                                    <td><a href="" style="font-size: 18px;" class="blue">{{info.topic}}</a></td>
                                    <td> {{info.description}} </td>
                                    <td> {{info.date_created}} </td>
                                    {% if user.is_authenticated%}
                                    <td> <button id={{info.tid}} onclick="openThread(this);" class="btn btn-outline-danger">Reply</button></td>
                                    
                                    <td> <button id={{info.tid}} onclick="delete_thread(this);" class="btn btn-outline-danger">X</button></td>
                                    {%endif%}
                                    
                                </tr>
                            {%endfor%}
                            </tbody>
                            <tbody>
                                {%for info2 in thread2%}
                                    <tr>
                                        <td><a href="#" id={{info2.tid}} onclick="openThread(this);" style="font-size: 18px;">{{info2.topic}}</a></td>
                                        <td> {{info2.description}} </td>
                                        <td> {{info2.date_created}} </td>
                                        {% if user.is_authenticated%}
                                        <td> <button id={{info2.tid}} onclick="openThread(this);" class="btn btn-outline-danger">Reply</button></td>
                                        {%endif%}
                                        
                                    </tr>
                                {%endfor%}
                                </tbody>
                        </table>
                    {%endif%}
                {% if user.is_authenticated%}
                    {%if checker%}
                        <h3 class="float-left">
                            <a href="#newModal" data-toggle="modal" id = {{forum.fid}} class="btn btn-danger" title="Add Thread" onclick = set_val(this)>
                                Add Thread
                           </a>
                    
                                
                      
                        <br><br>
                    {%else%}

                    <div class="card-body">
                        <h3>You are not a member :( <a href="#nameModal" data-toggle="modal" class="btn btn-success" title="Add Thread" id={{forum.fid}} onclick="join_forum(this);">
                            Join Forum
                    </a></h3>
                            
                    </div>
                    {%endif%}

                    {%endif%} 
                </div>
                <button class="btn btn-danger" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">Forum Details</button>

                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
                  <div class="offcanvas-header">
                    <h5 id="offcanvasRightLabel">{{forum.topic}}</h5>
                    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                  </div>
                  <div class="offcanvas-body">
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                          <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Forum details</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Members</a>
                        </li>
                      </ul>
                      <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                            <br>
                            <div class="col-8">
                                <blockquote class="blockquote">
                                    <p class="mb-0">{{forum.description}}</p>
                                    <br>
                                    <footer class="blockquote-footer">Created by <cite title="Source Title"> {{forum.name}}</cite></footer>
                                  </blockquote>
                          <br>
                                
                        </div>
                        </div>
                        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                            
                            {%if member%}
                            <ul class="list-group list-group-flush">
                                {%for m in member%}
                                <li class="list-group-item">{{m.name}}</li>
                                {%endfor%}
                            </ul>
                            {%else%}
                            <div class="card-body">
                                <h1 class="card-title">No members yet </h1>
                            </div>
                            {%endif%}
                                    
                                </div>
                            </div>
                            <br><br>
                            {%if checker%}
                            <div class="float-left">
                                <a href="#exitModal" data-toggle="modal" class="btn btn-danger" title="Add Thread" id={{forum.fid}} onclick="exit_forum(this);">
                                    Exit Forum
                            </a>
                            </div>
                            <br>
                            {%else%}
                            <div class="float-right">
                                <a href="#nameModal" data-toggle="modal" class="btn btn-success" title="Add Thread" id={{forum.fid}} onclick="join_forum(this);">
                                    Join Forum
                            </a>
                            </div>
                            {%endif%}
                  </div>
                </div>
                
      

  <div class="modal fade" id="newModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Provide Thread Details</h4>
            </div>
            <div class="modal-body">
                <form method="POST" role="form">
                    {%csrf_token%}
                    <div class="form-group">
                        <label for="name">Thread Name</label>
                        <br>
                            <input type="text" name="topic" id="topic">
                    </div>
                    <input type="number" name="forum_id" id="forum_id">
                    <div class="form-group" >
                        <label for="description">Description</label>
                        <br>
                            <textarea name="description" id="description" cols="30" rows="10"></textarea>
                    </div>
                    
                   <button type="submit" formaction="{% url 'forum:new_thread' %}" class="btn btn-outline-danger">Submit</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="nameModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">What do you want to be called?</h4>
            </div>
            <div class="modal-body">
                <form method="POST" role="form">
                    {%csrf_token%}
                    <div class="form-group">
                        <label for="name">Preferred Display Name</label>
                        <br>
                            <input type="text" name="name1" id="name1">
                    </div>
                    <div class="form-group">
                            <input type="number" name="forum_id1" id="forum_id1">
                    </div>
                    <button type="submit" formaction="{% url 'forum:join_forum' %}" class="btn btn-outline-danger">Submit</button>
                </form>
             
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>  
<div class="modal fade" id="exitModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <form method="POST" role="form">
                    {%csrf_token%}
                    <div class="form-group">
                        <label for="name">Are you sure?</label>
                    </div>
                    <div class="form-group">
                            <input type="number" name="forum_id2" id="forum_id2">
                    </div>
                    <button type="submit" formaction="{% url 'forum:exit_forum' %}" class="btn btn-outline-danger">Yes</button>
                    <button type="button" class="btn btn-outline-danger" data-dismiss="modal">No</button>
                </form>
             
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>              

    <script>
        function openThread(what) {
            
            var m = what.id;
            console.log(m);
            document.location.href = "{% url 'forum:open_thread' 1234 %}".replace(/1234/, m.toString());
        }
        function delete_thread(what) {
            
            var m = what.id;
            console.log(m);
            document.location.href = "{% url 'forum:delete_thread' 1234 %}".replace(/1234/, m.toString());
        }
        function set_val(what) {
            document.getElementById("forum_id").value = what.id;
            document.getElementById("forum_id").style.display ="none";
        }
        function join_forum(what) {
            document.getElementById("forum_id1").value = what.id;
            document.getElementById("forum_id1").style.display ="none";
        }
        function exit_forum(what) {
            document.getElementById("forum_id2").value = what.id;
            document.getElementById("forum_id2").style.display ="none";
        }
    </script>

 {% endblock %}   

FORUM/templates/index.html
{% extends 'base.html'%}

{% block content %}
<style>
    a{
        color: white;
    }
    .title
    {
        padding: 150px;
        text-align: center;
        color: white;
        height: 500px;
        width: 100%;
        background-image: url("https://png.pngtree.com/thumb_back/fw800/back_our/20190623/ourmid/pngtree-red-black-business-atmosphere-business-card-background-image_239813.jpg");
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>
<div class="title">
    {% if user.is_authenticated %}
    <h1>MITSOverflow</h1><br>
        <a href="#newModal" data-toggle="modal" class="btn btn-danger" title="Add Thread">
             Make a new Forum
        </a>
    {% else %}
    <p class="text-center" >Looks like you are new here</p>
    <a href="{% url 'register' %}" data-toggle="modal" class="btn btn-danger" title="Add Thread">
            Register
    </a>
    {% endif %}
        
</div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-lg-offset-0">
                    {% if user.is_authenticated%}
                    <div class="card-body">
                    <h3 class="card-title" style="color: white;text-align: center;"><strong>EXISTING FORUMS</strong></h1>
                    </div>
                    <br>
                    <br>
                    {%else%}
                    <div class="card-body">
                        <p style="color: white;text-align: center;">
                            MITSOverflow is a community for MITS students to share information and ask questions.<br>
                            1.Register using your MITS ID
                        </p>
                {%endif%}
                {%if item%}
                {% if user.is_authenticated%}
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                        <th scope="col">Forum Name</th>
                        <th scope="col">Creator</th>
                        <th scope="col">Description</th>
                        <th scope="col">Created on</th>
                        <th scope="col">Privacy</th>
                        <th>Reply</th>
                        {%endif%}
                      </tr>
                    </thead>
                    <tbody>
                {% if user.is_authenticated%}
                    {%for info in item%}
                      <tr>
                        <td><a href="#" id={{info.fid}} onclick="open_forum(this);" style="font-size: 18px;">{{info.topic}}</a></td>
                        <td> {{info.name}} </td>
                        <td> {{info.description}} </td>
                        <td> {{info.date_created}} </td>
                        <td>{{info.privacy}}</td>
                      
                        <td><a class="btn btn-outline-danger" id={{info.fid}} onclick="open_forum(this);">
                            View Forum
                       </a> </td>
                       {%endfor%}
                       {%endif%}    
                    </tr>
              
                    </tbody>
                  </table>
                {%endif%}

    <div class="modal fade" id="newModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <form method="POST" role="form">
                        {%csrf_token%}
                        <div class="form-group">
                            <label for="name">Display Name</label>
                            <br>
                                <input type="text" name="name" id="name">
                        </div>
                        <div class="form-group">
                            <label for="name">Thread Name</label>
                            <br>
                                <input type="text" name="topic" id="topic">
                        </div>
                        <div class="form-group" >
                            <label for="description">Description</label>
                            <br>
                                <textarea name="description" id="description" cols="30" rows="10"></textarea>
                        </div>
                        <div class="form-group" >
                        
                            <label for="Privacy">Privacy</label>
                            <br>
                            <label for="Private">Private</label>
                            <input type="radio" id="Private" value="Private" name="privacy">    
                            <label for="Public">Public</label>
                            <input type="radio" id="Public" value="Public" name="privacy">
                        </div>
                        <button type="submit" formaction="{% url 'forum:new_forum' %}" class="btn btn-outline-danger">Submit</button>
                        
                    </form>
                 
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    
    <script>
        function open_forum(what) {
            
            var m = what.id;
            console.log(m);
            document.location.href = "{% url 'forum:open_forum' 1234 %}".replace(/1234/, m.toString());
        }
    </script>

 {% endblock %}   